#!/usr/bin/env python3
"""Dump public.* table columns from a live rating Postgres into markdown.

Usage:
  DATABASE_URL=postgresql://... python scripts/introspect_postgres_schema.py
  python scripts/introspect_postgres_schema.py --out docs/schema/postgres_live.md

Requires psycopg2 and a restored rating-db. The output is a snapshot appendix
for docs/schema/postgres.md — commit only when intentionally refreshing.
"""
from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Tables this project touches (not full rating-db catalog)
TABLES = (
    "players",
    "teams",
    "tournaments",
    "tournament_results",
    "tournament_rosters",
    "tournament_editors",
    "true_dls",
    "ndcg",
)


def fetch_schema(database_url: str) -> str:
    import psycopg2

    conn = psycopg2.connect(database_url)
    cur = conn.cursor()
    lines = [
        "# PostgreSQL live schema snapshot",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "> Auto-generated by `scripts/introspect_postgres_schema.py`. "
        "Do not edit by hand; regenerate after rating-db schema changes.",
        "",
    ]
    for table in TABLES:
        cur.execute(
            """
            SELECT column_name, data_type, is_nullable
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = %s
            ORDER BY ordinal_position
            """,
            (table,),
        )
        rows = cur.fetchall()
        lines.append(f"## `public.{table}`")
        lines.append("")
        if not rows:
            lines.append("_table not found_")
            lines.append("")
            continue
        lines.append("| column | type | nullable |")
        lines.append("|--------|------|----------|")
        for col, dtype, nullable in rows:
            lines.append(f"| `{col}` | {dtype} | {nullable} |")
        lines.append("")
    conn.close()
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Write markdown to this path (default: stdout)",
    )
    parser.add_argument(
        "--database-url",
        default=os.environ.get(
            "DATABASE_URL", "postgresql://postgres:password@127.0.0.1:5432/postgres"
        ),
    )
    args = parser.parse_args()
    try:
        md = fetch_schema(args.database_url)
    except Exception as e:
        print(f"introspect failed: {e}", file=sys.stderr)
        return 1
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(md, encoding="utf-8")
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        print(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
